# Okay Lets Actually Do Some Linear Algebra Now...

I've already spoken about the importance of linear algebra in the module, and in the interest of time I'll skip on it for now. Lets get right to it..

**Matrices**

A matrix is simply a table of numbers.

Example

$A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{bmatrix}$


Notice how vectors were a collection of *numbers*, and now matrices are collections of *vectors*. Matrices describe transformations.

They can: 
- Rotate vectors
- Scale vectors
- Transform coordinate frames
- Solve systems of equations

*Almost every aerospace algorithm revolves around matrices.*

**Matrix additon works the same way as vector addition:** 

$A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{bmatrix}$
$B = \begin{bmatrix} 1 & 1 & 1 \\ 1 & 1 & 1 \\ 1 & 1 & 1 \end{bmatrix}$

$A + B = \begin{bmatrix} (1+1) & (2+1) & (3+1) \\ (4+1) & (5+1) & (6+1) \\ (7+1) & (8+1) & (9+1) \end{bmatrix} = \begin{bmatrix} 2 & 3 & 4 \\ 5 & 6 & 7 \\ 8 & 9 & 10 \end{bmatrix}$



Python Notation: 

In [1]:
import numpy as np
A = np.array([[1, 2, 3],[4, 5, 6], [7,8,9]])
B = np.array([[1,1,1],[1,1,1],[1,1,1]])


print(A)
print(B)
print(A +B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


**Matrix multiplication: matrix by vector**