# Okay Lets Actually Do Some Linear Algebra Now...

I've already spoken about the importance of linear algebra in the previous module, and in the interest of time I'll skip on it for now. Lets get right to it..

**Matrices**

A matrix is simply a table of numbers.

Example

$A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{bmatrix}$


Notice how vectors were a collection of *numbers*, and now matrices are collections of *vectors*. Matrices describe transformations.

They can: 
- Rotate vectors
- Scale vectors
- Transform coordinate frames
- Solve systems of equations

*Almost every aerospace algorithm revolves around matrices.*

**Matrix additon works the same way as vector addition:** 

$A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{bmatrix}$
$B = \begin{bmatrix} 1 & 1 & 1 \\ 1 & 1 & 1 \\ 1 & 1 & 1 \end{bmatrix}$

$A + B = \begin{bmatrix} (1+1) & (2+1) & (3+1) \\ (4+1) & (5+1) & (6+1) \\ (7+1) & (8+1) & (9+1) \end{bmatrix} = \begin{bmatrix} 2 & 3 & 4 \\ 5 & 6 & 7 \\ 8 & 9 & 10 \end{bmatrix}$



In python... 

In [3]:
import numpy as np
A = np.array([[1, 2, 3],[4, 5, 6], [7,8,9]])
B = np.array([[1,1,1],[1,1,1],[1,1,1]])


print(A)
print(B)
print(A + B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


**Matrix Shapes**

Before multiplying matrices, you need to keep track of shape.

A matrix with $m$ rows and $n$ columns is called an $m \times n$ matrix.

$A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}$

This matrix has 2 rows and 3 columns, so its shape is $2 \times 3$.

In python....

In [4]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

print(A)
print(A.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


For GNC, shape matters a lot because matrix multiplication only works when the inside dimensions match.

$(m \times n)(n \times p) = (m \times p)$

So a $2 \times 3$ matrix can multiply a $3 \times 1$ vector, and the answer will be $2 \times 1$.

An easy way to remember is if the *inner* dimensions match it works!

**Matrix multiplication: matrix by vector**

This is probably the most important one to understand first.

A matrix can take in a vector and output a new vector. This is why we say matrices describe transformations.

$A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}$

$x = \begin{bmatrix} 5 \\ 6 \end{bmatrix}$

$Ax = \begin{bmatrix} (1*5) + (2*6) \\ (3*5) + (4*6) \end{bmatrix} = \begin{bmatrix} 17 \\ 39 \end{bmatrix}$

Each row of the matrix gets dotted with the vector. It's as if the vector distributed itself to the matrix.

Now in python....

In [ ]:
A = np.array([[1, 2],
              [3, 4]])

x = np.array([5, 6])

answer = A @ x

print(answer)

In numpy, the `@` symbol means matrix multiplication.

This is different from `*`, which multiplies element by element. 

In [2]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[10, 10],
              [10, 10]])

print(A * B)
print(A @ B)

[[10 20]
 [30 40]]
[[30 30]
 [70 70]]


### 🎯 Your Turn

Create a 2 by 2 matrix and a 2 element vector.

Then multiply them using `@` and print the answer.

In [ ]:
# Write your code here
### BEGIN SOLUTION
A = np.array([[3, 1],
              [0, 2]])

x = np.array([4, 5])

answer = A @ x

print(answer)
### END SOLUTION

**Matrix multiplication: matrix by matrix**

Matrix by matrix multiplication works the same way, but instead of only transforming one vector, you can think of it as transforming multiple vectors at once.

$A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}$

$B = \begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix}$

$AB = \begin{bmatrix} (1*5)+(2*7) & (1*6)+(2*8) \\ (3*5)+(4*7) & (3*6)+(4*8) \end{bmatrix}$

$AB = \begin{bmatrix} 19 & 22 \\ 43 & 50 \end{bmatrix}$

Now in python....

In [ ]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print(A @ B)

Important note: matrix multiplication is **not commutative**.

That means:

$AB \neq BA$

This is not the same as multiplication you've learned with scalar numbers. Order matters. This is especially important for rotations and coordinate transforms. Again...more on what those mean later 😉. 

In [ ]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print(A @ B)
print(B @ A)

**Identity Matrix**

The identity matrix is the matrix version of multiplying by 1.

$I = \begin{bmatrix} 1 & 0 \\ 0 & 1 \end{bmatrix}$

If you multiply a vector by the identity matrix, nothing changes.

$Ix = x$

Now in python....

In [ ]:
I = np.eye(3)

x = np.array([10, 20, 30])

print(I)
print(I @ x)

**Transpose**

The transpose flips rows and columns.

$A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}$

$A^T = \begin{bmatrix} 1 & 4 \\ 2 & 5 \\ 3 & 6 \end{bmatrix}$

In GNC you will see transposes all the time, especially with covariance matrices and filters. We will get back on what those are 😊. 

Now in python....

In [ ]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])

print(A)
print(A.T)

**Inverse Matrix**

An inverse matrix is like undoing a matrix multiplication.

If:

$Ax = b$

then:

$x = A^{-1}b$

This is useful when solving linear systems. Theres many ways to do this, and theres something also called a pseudo-inverse which is almost an inverse but not quite. In practice though, you usually should not manually compute the inverse unless you need it for learning or explanation...its very computationally intensive. 

Now in python....

In [5]:
A = np.array([[2, 0],
              [0, 4]])

b = np.array([10, 20])

A_inverse = np.linalg.inv(A)
x = A_inverse @ b

print(A_inverse)
print(x)

[[0.5  0.  ]
 [0.   0.25]]
[5. 5.]


### 🎯 Your Turn 

Create a 2 by 2 matrix $A$ and a vector $b$.

Then:

- Find $A^{-1}$
- Multiply $A^{-1}b$
- Print the answer

Try to pick a matrix that is not just the identity matrix.

In [ ]:
# Write your code here
### BEGIN SOLUTION
A = np.array([[4, 7],
              [2, 6]])

b = np.array([1, 2])

A_inv = np.linalg.inv(A)

x = A_inv @ b

print(A_inv)
print(x)
### END SOLUTION

A better way to solve $Ax = b$ in code is with `np.linalg.solve`.

It gives the same answer, but it is usually cleaner and more numerically stable.

In [ ]:
A = np.array([[2, 0],
              [0, 4]])

b = np.array([10, 20])

x = np.linalg.solve(A, b)

print(x)

### 🚀 Challenge: The Final Matrix Boss

Use the following matrices and vector:

$A = \begin{bmatrix} 2 & 1 \\ 4 & 3 \end{bmatrix}$

$B = \begin{bmatrix} 1 & 0 \\ 2 & 1 \end{bmatrix}$

$b = \begin{bmatrix} 5 \\ 11 \end{bmatrix}$

Your Tasks:

- Print the shape of $A$
- Compute $A + B$
- Compute $AB$ using `@`
- Compute $BA$ using `@`
- Compute $A^T$ using `.T`
- Solve $Ax = b$ using `np.linalg.solve`

Then compare $AB$ and $BA$ — print whether they are the same.

In [ ]:
#% checker: matrix_boss
import numpy as np

A = np.array([[2, 1],
              [4, 3]])

B = np.array([[1, 0],
              [2, 1]])

b = np.array([5, 11])

# Write your code here
### BEGIN SOLUTION
print("Shape of A:", A.shape)

print("A + B:")
print(A + B)

AB = A @ B
BA = B @ A

print("AB:")
print(AB)
print("BA:")
print(BA)

print("A transpose:")
print(A.T)

x = np.linalg.solve(A, b)
print("Solution of Ax = b:", x)

print("Is AB the same as BA?", np.array_equal(AB, BA))
### END SOLUTION

**OKAY....this might have been alot to take it. Take a deep breath...😮‍💨**

To summarize. At this point, the main ideas to be comfortable with are:

- Matrix shape
- Matrix-vector multiplication
- Matrix-matrix multiplication
- Transpose
- Inverses
- Solving $Ax = b$

That is enough linear algebra to start recognizing what is happening when matrices show up in later topics...wink. This ends the fundamentals you need. Starting from the next module, we will start talking specifically about GNC topics! 